version: '3.5'

services:
    postgres:
      restart: always
      image: postgres:13.4-alpine
      environment:
        POSTGRES_USER: ${POSTGRES_USER:-postgres}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres1234}
        PGDATA: /data/postgres
      volumes:
        - ./assets/db/create.sql:/docker-entrypoint-initdb.d/create.sql
      ports:
        - "54321:5432"
    nats:
      command:
        - "--cluster"
        - "nats://0.0.0.0:6222"
        - "--cluster_id"
        - test-cluster
        - "--clustered"
        - "--cluster_bootstrap"
        - "--cluster_log_path"
        - /data/log
        - "--cluster_node_id"
        - nats-streaming-1
        - "--cluster_raft_logging"
        - "--debug"
        - "--dir"
        - /data/msg
        - "--http_port"
        - "8222"
        - "--port"
        - "4222"
        - "--store"
        - file
        - "--stan_debug"
        - "--hb_interval"
        - 2s
        - "--hb_fail_count"
        - "1"
        - "--hb_timeout"
        - 5s
      image: "nats-streaming:0.17.0"
      ports:
        - "8222:8222"
        - "4222:4222"
networks:
  default:
